export const genreNames = [
  "Suspense",
  "Action",
  "Comedy",
  "Documentary",
  "Drama",
  "Fantasy",
  "Horror",
  "Musical",
  "Mystery",
  "Romance",
  "Science Fiction",
  "Thriller",
  "Western",
  "Adventure",
  "Gaming",
  "Crime",
  "Traditional",
  "Religious",
  "Sports",
  "Politics",
  "Philosophy",
  "History",
  "Biography",
  "War",
  "Animation",
];

export const customerNames = [
  "Lois Lane",
  "Clark Kent",
  "Kara Denvers",
  "Ralph Kramden",
  "Alice Kramden",
  "Holly Golightly",
  "Liza Doolittle",
  "Henry Higgins",
  "Joseph Arimathea",
  "Mary Magdalene",
  "Simon Cyrene",
  "Dixie Normous",
  "Felicity Shagwell",
  "Ivana Humpalot",
  "Plenty OToole",
  "Tiffany Case",
  "Shady Tree",
  "Kissy Suzuki",
  "Pussy Galore",
  "Honey Ryder",
  "Sylvia Trench",
  "Lupe Lamora",
  "May Day",
  "Jenny Flex",
  "Penelope Smallbone",
];
